homepage:
  path: /
  controller: AppBundle\Controller\DefaultController::indexAction

pokedex:
  path: /pokemon/{id}
  controller: AppBundle\Controller\DefaultController::pokemonDetailAction

pokedex_ajax:
  path: /pokemon/ajax/{id}
  controller: AppBundle\Controller\DefaultController::pokemonAjaxAction